In [ ]:
import numpy as np
import pandas as pd
from auditory_cortex.neural_data import NormalizerCalculator, create_neural_metadata
from auditory_cortex.analyses import Correlations


numexpr.utils - INFO - Note: NumExpr detected 20 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
numexpr.utils - INFO - NumExpr defaulting to 8 threads.


In [17]:
layer = '2'
data_dict = {
    'layer_ids': 4* [layer],
    'channel_ids': np.array([0, 1, 2, 3]),
    'session': np.array([200206, 200206, 200206, 200206]),
    'corr_scores': np.array([0.1, 0.2, 0.3, 0.4]),
}
df = pd.DataFrame(data_dict)
df

layer_ids  channel_ids  session  corr_scores
0         2            0   200206          0.1
1         2            1   200206          0.2
2         2            2   200206          0.3
3         2            3   200206          0.4

In [18]:
df['layer_ids']

0    2
1    2
2    2
3    2
Name: layer_ids, dtype: object

In [16]:
dataset_name = 'ucsf'
normalizer = NormalizerCalculator(dataset_name)

In [17]:
session=200206
bin_width=50
mVocs=True
norm_dist, null_dist = normalizer.get_inter_trial_corr_dists_for_session(
    session, bin_width=bin_width, mVocs=mVocs
)

auditory_cortex.neural_data.normalizer_calculator - INFO - Getting normalizer dist. for sess-200206, bw-50, mVocs=True


In [ ]:
data_dict = {
    'session': session,
    'bin_width': bin_width,
    'channel_ids'
    'norm_dist': norm_dist,
    'null_dist': null_dist
}

In [13]:
model_name = 'cochcnn9'
identifier = 'ucsf_reset_mVocs_trf_lags200_bw50_regression_improved_permuted'
corr = Correlations(model_name+'_'+identifier)

In [14]:
corr.data

session  layer  channel  bin_width  delay  test_cc_raw  normalizer  \
0      180413.0    0.0      0.0       50.0    0.0          0.0         0.0   
1      180413.0    0.0      1.0       50.0    0.0          0.0         0.0   
2      180413.0    0.0      2.0       50.0    0.0          0.0         0.0   
3      180413.0    0.0      3.0       50.0    0.0          0.0         0.0   
4      180413.0    0.0      4.0       50.0    0.0          0.0         0.0   
...         ...    ...      ...        ...    ...          ...         ...   
14341  200318.0    8.0     40.0       50.0    0.0          0.0         0.0   
14342  200318.0    8.0     41.0       50.0    0.0          0.0         0.0   
14343  200318.0    8.0     42.0       50.0    0.0          0.0         0.0   
14344  200318.0    8.0     43.0       50.0    0.0          0.0         0.0   
14345  200318.0    8.0     44.0       50.0    0.0          0.0         0.0   

       mVocs_test_cc_raw  mVocs_normalizer  opt_lag  opt_lmbda  N_sents  \
0          -2.045651e-02         -0.007198    200.0        1.0    500.0   
1          -2.298020e-06          0.002096    200.0       14.0    500.0   
2           1.299994e-02         -0.001019    200.0        2.0    500.0   
3          -2.465553e-08         -0.004867    200.0       15.0    500.0   
4           3.922648e-02         -0.010654    200.0        2.0    500.0   
...                  ...               ...      ...        ...      ...   
14341       2.597478e-02          0.109254    200.0        3.0    500.0   
14342       1.362345e-01          0.066384    200.0        1.0    500.0   
14343       1.785518e-03          0.114778    200.0        1.0    500.0   
14344       9.375573e-02          0.081775    200.0        0.0    500.0   
14345       8.100141e-02          0.069362    200.0        1.0    500.0   

       mVocs_null_mean  mVocs_null_std layer_type  mVocs_normalized_test_cc  
0             0.004282        0.113042       conv                       NaN  
1            -0.007042        0.081968       conv                 -0.000050  
2             0.001140        0.076688       conv                       NaN  
3            -0.004299        0.074310       conv                       NaN  
4            -0.000890        0.078888       conv                       NaN  
...                ...             ...        ...                       ...  
14341         0.045603        0.087255       conv                  0.078584  
14342         0.002156        0.069096       conv                  0.528758  
14343         0.029390        0.076957       conv                  0.005270  
14344         0.004187        0.076258       conv                  0.327859  
14345         0.007857        0.073067       conv                  0.307561  

[14346 rows x 16 columns]

In [6]:
norm_dist, null_dist = normalizer._compute_inter_trial_corr_dists(
    200206, 50, 1000
)

auditory_cortex.neural_data.ucsf_data.ucsf_dataset - INFO - NeuralData:  Creating object for session: 200206 ... 
auditory_cortex.neural_data.ucsf_data.ucsf_dataset - INFO - Done.


In [8]:
ch = 0
norm_dist[ch].shape

(50000,)

In [9]:
ch = 0
null_dist[ch].shape

(50000,)

In [10]:
repeated_spikes = normalizer.get_repeated_spikes(3, 50)

In [11]:
repeated_spikes.keys()

dict_keys(['103-fmjf0_si1254.wfm', '120-frew0_si1030.wfm', '124-fsah0_si1874.wfm', '13-fcaj0_si1804.wfm', '138-ftaj0_si1329.wfm', '142-ftmg0_si2162.wfm', '145-fvkb0_si1789.wfm', '148-mabw0_si2294.wfm', '151-maeo0_si1956.wfm', '153-majc0_si2095.wfm', '16-fcft0_si1808.wfm', '164-mbcg0_si486.wfm', '174-mbom0_si1644.wfm', '183-mccs0_si2099.wfm', '186-mcem0_si1398.wfm', '187-mchh0_si1634.wfm', '189-mcmb0_si1898.wfm', '193-mctm0_si720.wfm', '195-mctw0_si2003.wfm', '206-mdhs0_si1530.wfm', '240-meal0_si2177.wfm', '263-mges0_si1481.wfm', '278-mjar0_si2247.wfm', '292-mjeb0_si656.wfm', '308-mjmm0_si625.wfm', '315-mjrh0_si1125.wfm', '340-mklt0_si583.wfm', '345-mljc0_si1855.wfm', '360-mmdm1_si2043.wfm', '362-mmds0_si1973.wfm', '373-mmrp0_si2034.wfm', '387-mpgh0_si924.wfm', '394-mrab0_si1224.wfm', '396-mram0_si1905.wfm', '4-fawf0_si1000.wfm', '401-mrdm0_si1595.wfm', '402-mrds0_si1167.wfm', '404-mreh1_si2229.wfm', '41-fdrw0_si1423.wfm', '412-mrgg0_si1199.wfm', '440-mrxb0_si1585.wfm', '484-mvrw0_si211

In [12]:
stim_ids=None
num_trials=None

if stim_ids is None:
    stim_ids = list(repeated_spikes.keys())
channel_ids = list(repeated_spikes[stim_ids[0]].keys())
total_trial_repeats = repeated_spikes[stim_ids[0]][channel_ids[0]].shape[0]
trial_ids = np.arange(total_trial_repeats)

In [13]:
num_itr = 1000

In [16]:
channel_ids = ['a', 'b']
norm_dists = {ch: np.zeros((num_itr,)) for ch in channel_ids}

In [ ]:
seq_U = {ch: [] for ch in channel_ids}
seq_V = {ch: [] for ch in channel_ids}

stim_ids = np.random.permutation(stim_ids)

np.random.randint()






for stim_id in np.random.permutation(stim_ids):
    tr1, tr2 = np.random.choice(trial_ids, size=2, replace=False)
    for ch in channel_ids:
        seq_U[ch].append(repeated_spikes[stim_id][ch][tr1])
        seq_V[ch].append(repeated_spikes[stim_id][ch][tr2])

In [8]:
num_stim = len(stim_ids)

In [21]:
import time

START_TIME = time.time()
num_stim_ids = 1500
trials = np.arange(10)
select_samples = []
for i in range(num_stim_ids):
    tr1, tr2 = np.random.choice(trials, size=2, replace=False)
    select_samples.append((tr1, tr2))

# print(select_samples)

print(f"Time taken to select samples: {(time.time() - START_TIME)*1000:.2f} ms")



Time taken to select samples: 23.21 ms


In [22]:
import time

START_TIME = time.time()
samples = np.array([
    np.random.choice(trial_ids, size=2, replace=False)
    for _ in range(num_stim_ids)]
)
print(f"Time taken to select samples: {(time.time() - START_TIME)*1000:.2f} ms")

Time taken to select samples: 21.86 ms


In [34]:
trial_ids.shape

(11,)

In [80]:
trials_2d = np.repeat(trial_ids[None,:], num_stim_ids, axis=0)

In [81]:
trials_2d[:3,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [77]:
idx = np.random.randint(0, len(trial_ids), size=(num_stim_ids, 2))

In [84]:
trials_2d.shape

(1500, 11)

In [91]:
rows = np.arange(num_stim_ids)[:, None]
selected = trials_2d[rows,idx]

In [92]:
selected[:5, :]

array([[ 5,  4],
       [10,  4],
       [ 4,  1],
       [ 0,  5],
       [ 9,  2]])

In [75]:
np.random.permutation(trials_2d[:,:3])

array([[ 0,  0,  0],
       [ 7,  7,  7],
       [ 8,  8,  8],
       [ 6,  6,  6],
       [ 5,  5,  5],
       [ 4,  4,  4],
       [ 3,  3,  3],
       [ 2,  2,  2],
       [ 9,  9,  9],
       [ 1,  1,  1],
       [10, 10, 10]])

In [54]:
rand = np.random.permutation(np.tile(trial_ids, (num_stim_ids, 1)).transpose())

In [58]:
rand[:2, :10]

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [33]:
trial_ids_2d.shape

(1, 16500)

In [25]:
trial_ids.shape

(11,)

In [26]:
samples = np.random.choice(trial_ids_2d, size=(num_stim_ids, 2), replace=False)

ValueError: a must be 1-dimensional

In [10]:
num_itr=100000

In [ ]:
stim_ids = list(repeated_spikes.keys())
channel_ids = list(repeated_spikes[stim_ids[0]].keys())
total_trial_repeats = repeated_spikes[stim_ids[0]][channel_ids[0]].shape[0]

norm_dists = {ch: np.zeros((num_itr,)) for ch in channel_ids}
null_dists = {ch: np.zeros((num_itr,)) for ch in channel_ids}
trial_ids = np.arange(total_trial_repeats)


In [ ]:
seq_U = {ch: [] for ch in channel_ids}
seq_V = {ch: [] for ch in channel_ids}
for stim_id in np.random.permutation(stim_ids):
    tr1, tr2 = np.random.choice(trial_ids, size=2, replace=False)
    for ch in channel_ids:
        seq_U[ch].append(repeated_spikes[stim_id][ch][tr1])
        seq_V[ch].append(repeated_spikes[stim_id][ch][tr2])
for ch in channel_ids:
    U = np.concatenate(seq_U[ch], axis=0).squeeze()
    V = np.concatenate(seq_V[ch], axis=0).squeeze()

    corr_ch = NormalizerCalculator.safe_corrcoef(U, V) 
    norm_dists[ch][itr] = corr_ch
    
    V_shifted = np.roll(V, V.shape[0]//2, axis=0)
    null_ch = NormalizerCalculator.safe_corrcoef(U, V_shifted) 
    null_dists[ch][itr] = corr_ch



In [19]:
ch = channel_ids[0]
U = np.concatenate(seq_U[ch], axis=0).squeeze()
V = np.concatenate(seq_V[ch], axis=0).squeeze()

In [20]:
U.shape

(331,)

In [ ]:
rand_stim_ids = np.random.permutation(stim_ids)
tr1, tr2 = np.random.choice(trial_ids, size=2, replace=False)
for ch in channel_ids:
    
    
    stim_id = rand_stim_ids[i % len(rand_stim_ids)]
    channel_wise_dists[ch][i] = np.corrcoef(
        seq_U[ch][tr1], seq_V[ch][tr2])[0, 1]

In [15]:
seq_U[channel_ids[0]].shape, seq_V[channel_ids[0]].shape

((331,), (331,))

In [ ]:
for itr in range(num_itr):
    long_seq1 = []
    long_seq2 = []
    for stim_id in np.random.permutation(stim_ids):
        spikes = repeated_spikes[stim_id]
        tr1, tr2 = np.random.choice(trial_ids, size=2, replace=False)

In [6]:
# seq_1 = np.random.rand(100)  # Example sequence 1
# seq_2 = np.random.rand(100)  # Example sequence 1

seq_1 = np.zeros(100)  # Example sequence 1
seq_2 = np.zeros(100)  # Example sequence 1

corr_ch = np.corrcoef(seq_1, seq_2)[0,1]
print(corr_ch)

nan


/home/ahmedb/.conda/envs/cent7/2020.11-py38/wav2letter/lib/python3.8/site-packages/numpy/lib/function_base.py:2829: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
